### ISSUE TITLE
Code Start ยังจำเป็นต้องใส่อยู่หรือไหม ?

### ISSUE THREAD

**Issue by phurinaix** [pingping-n/SF312_Project#3]
code start ยังจำเป็นต้องใส่อยู่หรือไม่ครับ
แล้วถ้าใส่ ต้องให้ user พิมพ์ว่าอะไรลงไปครับ ?

**Comment by peterparkers** [comment]
? ? ?

**Comment by pingping-n** [comment]
ยังต้องใส่ครับผม
รหัส DM มาครับ
