### ISSUE TITLE
มีเงื่อนไขอะไรบ้างครับ ? ในการเช็คว่าสภาพอากาศดี สามารถปล่อยยานได้

### ISSUE THREAD

**Issue by phurinaix** [pingping-n/SF312_Project#9]
จากไฟล์ weather.txt
มีองค์ประกอบ ภายในไฟล์คือ

- weather (สภาพอากาศ) : **เช็คอย่างไร ?**
- pressure (ความดันอากาศ) : **เช็คอย่างไร ?**
- temperature (อุณหภูมิ) : **เช็คอย่างไร ?**
- wind (ความเร็วลม) : **เช็คอย่างไร ?**
- visibility (วิสัยการมองเห็น) : **เช็คอย่างไร ?**

> **จะทำการเช็คข้อมูลอย่างไรครับว่าสภาพอากาศพร้อม**

**Comment by pingping-n** [comment]
weather (สภาพอากาศ) : Clear, Mostly Clear  เมฆต้องน้อยๆ
pressure (ความดันอากาศ) : 1000-1018 hPa
temperature (อุณหภูมิ) : 15-35 Celsius
wind (ความเร็วลม) : ไม่เกิน 0-15 m/s
visibility (วิสัยการมองเห็น) :  ต้องเกิน 8 km ขึ้นไป

**Comment by phurinaix** [comment]
ขอบคุณคับ
